
spring.security.user.name=satyam
spring.security.user.password=1234

spring.servlet.session.cookie.same=strict


spring.datasource.url=jdbc:postgresql://localhost:5432/Mentor_scheduler
spring.datasource.username=postgres
spring.datasource.password=satyam721
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

